name = "cases-theme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Tema Hugo per a cases vacacionals a Lanzarote, multidioma i Netlify-ready."
homepage = "https://housesinlanzarote.eu"
min_version = "0.123.0"

[author]
  name = "Ignasi Nogués"
  homepage = "https://www.linkedin.com/in/ignasi-nogues/"